Repository EventFahrplan/EventFahrplan, pull requests merged in 2018-11, with the labels that each got.

#87 Fix crash when EventDetailFragment attempts to be load with an non existing "event_id".
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/AbstractListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetail.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
Labels: Bug fix

#86 Adaptive launcher icon
  app/src/ccc34c3/ic_launcher-web.png
  app/src/ccc34c3/res/drawable-v24/ic_launcher_background.xml
  app/src/ccc34c3/res/drawable/ic_launcher_background.xml
  app/src/ccc34c3/res/drawable/ic_launcher_foreground.xml
  app/src/ccc34c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc34c3/res/mipmap-hdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-mdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xhdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xxhdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/ccc34c3/web_hi_res_512.png
  app/src/main/ic_launcher-web.png
  assets/launcher-background-34c3.svg
  assets/launcher-foreground-34c3.svg
Labels: Design, UX

#88 Use targetSdkVersion 26 (Oreo)
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup
