Repository EventFahrplan/EventFahrplan, pull requests merged in 2018-12, with the labels that each got.

#90 Revise WikiEventUtils.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleLectureFormat.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/wiki/WikiEventUtils.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/wiki/WikiEventUtils.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/wiki/WikiEventUtilsTest.kt
Labels: Housekeeping

#91 Revise EventUrlComposer.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/EventUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/EventUrlComposerTest.kt
Labels: Housekeeping

#94 35c3
  app/build.gradle
  app/gradle.properties.example
  app/src/ccc35c3/ic_launcher-web.png
  app/src/ccc35c3/res/drawable-anydpi-v24/ic_notification.xml
  app/src/ccc35c3/res/drawable-hdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-hdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-mdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-mdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-v24/ic_launcher_foreground.xml
  app/src/ccc35c3/res/drawable-xhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-xxhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xxhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-xxxhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xxxhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable/bell.png
  app/src/ccc35c3/res/drawable/ic_change_novideo.png
  app/src/ccc35c3/res/drawable/ic_change_video.png
  app/src/ccc35c3/res/drawable/ic_novideo.png
  app/src/ccc35c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc35c3/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/ccc35c3/res/mipmap-hdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-mdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xhdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xxhdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/ccc35c3/res/values-de/strings.xml
  app/src/ccc35c3/res/values/colors.xml
  app/src/ccc35c3/res/values/colors_congress.xml
  app/src/ccc35c3/res/values/ic_launcher_background.xml
  app/src/ccc35c3/res/values/strings.xml
  app/src/ccc35c3/res/xml/track_resource_names.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
  app/src/main/res/mipmap-hdpi/c3nav.png
  app/src/main/res/mipmap-mdpi/c3nav.png
  app/src/main/res/mipmap-xhdpi/c3nav.png
  app/src/main/res/mipmap-xxhdpi/c3nav.png
  app/src/main/res/mipmap-xxxhdpi/c3nav.png
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverterTest.java
  assets/fairydust-notification.svg
  assets/fairydust.svg
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/AlarmsDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/HighlightDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/LecturesDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/MetaDBOpenHelper.java
Labels: Project setup

#98 Fixed broken time column
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/Conference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/DateHelper.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ConferenceTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/DateHelperTest.kt
Labels: Bug fix, UX

#99 Update c3nav room mapping.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
Labels: Project setup

#111 Prevent IllegalStateException when zombie lecture is tapped in favorites.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
Labels: Bug fix

#112 Show app at the lock screen.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
Labels: Feature request

#118 Fix schedule feedback URL for Pretalx events.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/EventExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/EventUrlComposer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposerTest.kt
Labels: Bug fix

#119 Let users visually distinguish between past and upcoming favorites.
  app/src/ccc35c3/res/values/colors.xml
Labels: Bug fix, UX
