Repository EventFahrplan/EventFahrplan, pull requests merged in 2019-01, with the labels that each got.

#122 Add guidelines to contribute to the project.
  .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
  .github/ISSUE_TEMPLATE/CRASH_REPORT_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/BUG_FIX_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Project setup

#129 Use single pull request template since multiple templates are not presented to users.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/BUG_FIX_TEMPLATE.md
Labels: Project setup

#130 Simplify lecture filtering and counting.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMiscTest.kt
  app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Housekeeping

#131 RIP 34C3.
  app/build.gradle
  app/gradle.properties.example
  app/src/ccc34c3/ic_launcher-web.png
  app/src/ccc34c3/res/drawable-hdpi/dialog_logo.png
  app/src/ccc34c3/res/drawable-hdpi/ic_notification.png
  app/src/ccc34c3/res/drawable-mdpi/dialog_logo.png
  app/src/ccc34c3/res/drawable-mdpi/ic_notification.png
  app/src/ccc34c3/res/drawable-v24/ic_launcher_background.xml
  app/src/ccc34c3/res/drawable-xhdpi/dialog_logo.png
  app/src/ccc34c3/res/drawable-xhdpi/ic_notification.png
  app/src/ccc34c3/res/drawable-xxhdpi/dialog_logo.png
  app/src/ccc34c3/res/drawable-xxhdpi/ic_notification.png
  app/src/ccc34c3/res/drawable-xxxhdpi/dialog_logo.png
  app/src/ccc34c3/res/drawable-xxxhdpi/ic_notification.png
  app/src/ccc34c3/res/drawable/bell.png
  app/src/ccc34c3/res/drawable/ic_change_novideo.png
  app/src/ccc34c3/res/drawable/ic_change_video.png
  app/src/ccc34c3/res/drawable/ic_launcher_background.xml
  app/src/ccc34c3/res/drawable/ic_launcher_foreground.xml
  app/src/ccc34c3/res/drawable/ic_novideo.png
  app/src/ccc34c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc34c3/res/mipmap-hdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-mdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xhdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xxhdpi/ic_launcher.png
  app/src/ccc34c3/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/ccc34c3/res/values-de/strings.xml
  app/src/ccc34c3/res/values/colors.xml
  app/src/ccc34c3/res/values/colors_congress.xml
  app/src/ccc34c3/res/values/strings.xml
  app/src/ccc34c3/res/xml/track_resource_names.xml
  assets/launcher-background-34c3.svg
  assets/launcher-foreground-34c3.svg
Labels: Housekeeping, Project setup

#132 Update screenshot with 35C3 Schedule app.
  README.md
  gfx/EventFahrplan-33c3-Events-Tablet.png
  gfx/EventFahrplan-35c3-Events-Tablet-Phone.png
Labels: Design, Project setup

#133 Provide notifications settings shortcut in app settings.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values/preferences.xml
  app/src/main/res/xml/prefs.xml
Labels: Feature request, UX

#134 Update project setup
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: Project setup

#113 Enable multi-window support
  app/src/main/AndroidManifest.xml
Labels: Feature request, UX
