Repository EventFahrplan/EventFahrplan, pull requests merged in 2019-05, with the labels that each got.

#145 Updated README.md with table of contents and etc
  README.md
Labels: Documentation

#142 Reduces code duplication in database module
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/CursorExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SQLiteDatabaseExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/AlarmsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/LecturesDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/MetaDatabaseRepository.kt
Labels: Housekeeping, Persistence

#147 Compile against SDK 28
  .travis.yml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup
