Repository EventFahrplan/EventFahrplan, pull requests merged in 2019-10, with the labels that each got.

#183 Add Russian language
  app/src/main/res/values-ru/preferences.xml
  app/src/main/res/values-ru/strings.xml
Labels: Translation

#186 Feature/dutch translations
  app/src/ccc35c3/res/values-nl/strings.xml
  app/src/cccamp2019/res/values-nl/strings.xml
  app/src/main/res/values-nl/strings.xml
Labels: Hacktoberfest, Translation

#187 Add italian translations
  app/src/main/res/values-it/strings.xml
Labels: Hacktoberfest, Translation

#184 Limits the app activities to be displayed over lock screen
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetail.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
Labels: Bug fix, Hacktoberfest

#190 Spanish translation
  app/src/ccc35c3/res/values-es/strings.xml
  app/src/main/res/values-es/strings.xml
Labels: Hacktoberfest, Translation

#191 Add russian translation
  app/src/ccc35c3/res/values-ru/strings.xml
  app/src/cccamp2019/res/values-ru/strings.xml
Labels: Hacktoberfest, Translation
