Repository EventFahrplan/EventFahrplan, pull requests merged in 2019-12, with the labels that each got.

#192 Add icon for time and place
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/commons/TextViewCompat.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/res/drawable/ic_access_time.xml
  app/src/main/res/drawable/ic_room.xml
  app/src/main/res/layout/event_detailbar.xml
  app/src/main/res/layout/event_detailbar_large.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/placeholder.xml
  assets/access-time.svg
  assets/room.svg
Labels: Design, Hacktoberfest, UX

#198 Let the operating system check SSL/TLS certificates.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CustomHttpClient.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/SslSocketFactory.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
Labels: Networking

#199 Customize user agent to let the APIs identify requests made by the app.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CustomHttpClient.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/UserAgentInterceptor.kt
Labels: Networking

#201 36c3
  app/build.gradle
  app/gradle.properties.example
  app/src/ccc36c3/ic_launcher-playstore.png
  app/src/ccc36c3/res/drawable-anydpi-v24/ic_notification.xml
  app/src/ccc36c3/res/drawable-hdpi/dialog_logo.png
  app/src/ccc36c3/res/drawable-hdpi/ic_notification.png
  app/src/ccc36c3/res/drawable-mdpi/dialog_logo.png
  app/src/ccc36c3/res/drawable-mdpi/ic_notification.png
  app/src/ccc36c3/res/drawable-xhdpi/dialog_logo.png
  app/src/ccc36c3/res/drawable-xhdpi/ic_notification.png
  app/src/ccc36c3/res/drawable-xxhdpi/dialog_logo.png
  app/src/ccc36c3/res/drawable-xxhdpi/ic_notification.png
  app/src/ccc36c3/res/drawable-xxxhdpi/dialog_logo.png
  app/src/ccc36c3/res/drawable-xxxhdpi/ic_notification.png
  app/src/ccc36c3/res/drawable/bell.png
  app/src/ccc36c3/res/drawable/ic_change_novideo.png
  app/src/ccc36c3/res/drawable/ic_change_video.png
  app/src/ccc36c3/res/drawable/ic_launcher_foreground.xml
  app/src/ccc36c3/res/drawable/ic_novideo.png
  app/src/ccc36c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc36c3/res/mipmap-hdpi/ic_launcher.png
  app/src/ccc36c3/res/mipmap-mdpi/ic_launcher.png
  app/src/ccc36c3/res/mipmap-xhdpi/ic_launcher.png
  app/src/ccc36c3/res/mipmap-xxhdpi/ic_launcher.png
  app/src/ccc36c3/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/ccc36c3/res/values-de/strings.xml
  app/src/ccc36c3/res/values-es/strings.xml
  app/src/ccc36c3/res/values-nl/strings.xml
  app/src/ccc36c3/res/values-pt/strings.xml
  app/src/ccc36c3/res/values-ru/strings.xml
  app/src/ccc36c3/res/values/colors.xml
  app/src/ccc36c3/res/values/colors_congress.xml
  app/src/ccc36c3/res/values/ic_launcher_background.xml
  app/src/ccc36c3/res/values/strings.xml
  app/src/ccc36c3/res/xml/track_resource_names.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverterTest.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/AlarmsDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/HighlightDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/LecturesDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/MetaDBOpenHelper.java
Labels: Engelsystem, Navigation, Project setup

#206 Fix NullPointerException in UpdateService#onDestroy.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
Labels: Bug fix

#207 Update room mappings for c3nav.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
Labels: Navigation

#209 Automatically reload schedule if Engelsystem shifts URL is configured.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values/booleans.xml
  app/src/main/res/values/preferences.xml
Labels: Engelsystem, Feature request, UX

#208 Sanitize lectures
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensionsTest.kt
Labels: Engelsystem, Feature request

#217 Update room mappings for c3nav.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
Labels: Navigation

#219 Facilitate more verbose user feedback.
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Crash reporting

#214 Don't use MyApp.lectureList to populate EventDetailFragment
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/LecturesDatabaseRepository.kt
Labels: Bug fix, Persistence

#223 Ensure de/selecting a favorite in details is reflected in the main view.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
Labels: Bug fix

#221 Mitigates the effect of a SecurityException which can occur in JobIntentService.
  app/src/main/java/android/support/v4/app/SafeJobIntentService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
Labels: Bug fix

#220 Fix long room titles
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
Labels: Bug fix, UX
