Repository EventFahrplan/EventFahrplan, pull requests merged in 2019-09, with the labels that each got.

#156 Add missing content description for about dialog logo.
  app/src/camp2015/res/values-de/strings.xml
  app/src/camp2015/res/values/strings.xml
  app/src/ccc35c3/res/values-de/strings.xml
  app/src/ccc35c3/res/values/strings.xml
  app/src/cccamp2019/res/values-de/strings.xml
  app/src/cccamp2019/res/values/strings.xml
  app/src/main/res/layout-port/about_dialog.xml
  app/src/main/res/layout/about_dialog_land.xml
Labels: UX

#158 Enhance visual layout of event details screen.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensions.kt
Labels: Design, UX

#159 Favorites formatting
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/LectureArrayAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/LectureArrayAdapter.kt
  app/src/main/res/layout/lecture_change_row.xml
Labels: Design, UX

#160 Prevent event detailbar text to wrap into second line.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/res/layout/event_detailbar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Design, UX

#157 Fix Pretalx feedback URL.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/EventExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposerTest.kt
Labels: Bug fix

#163 Fix NullPointerException in EventDetailFragment#onViewCreated on tablets
  app/src/main/res/layout/event_detailbar.xml
  app/src/main/res/layout/event_detailbar_large.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values-xlarge/dimens.xml
Labels: Bug report

#164 Use targetSdkVersion 28 (Pie)
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/Contexts.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ConnectivityObserver.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#165 RIP Camp2015.
  app/build.gradle
  app/gradle.properties.example
  app/src/camp2015/res/drawable-hdpi/dialog_logo.png
  app/src/camp2015/res/drawable-hdpi/ic_actionbar_logo.png
  app/src/camp2015/res/drawable-hdpi/ic_notification.png
  app/src/camp2015/res/drawable-mdpi/ic_actionbar_logo.png
  app/src/camp2015/res/drawable-mdpi/ic_notification.png
  app/src/camp2015/res/drawable-xhdpi/dialog_logo.png
  app/src/camp2015/res/drawable-xhdpi/ic_actionbar_logo.png
  app/src/camp2015/res/drawable-xhdpi/ic_notification.png
  app/src/camp2015/res/drawable-xxhdpi/dialog_logo.png
  app/src/camp2015/res/drawable-xxhdpi/ic_actionbar_logo.png
  app/src/camp2015/res/drawable-xxhdpi/ic_notification.png
  app/src/camp2015/res/drawable/bell.png
  app/src/camp2015/res/drawable/ic_change_novideo.png
  app/src/camp2015/res/drawable/ic_change_video.png
  app/src/camp2015/res/drawable/ic_novideo.png
  app/src/camp2015/res/mipmap-hdpi/ic_launcher.png
  app/src/camp2015/res/mipmap-mdpi/ic_launcher.png
  app/src/camp2015/res/mipmap-xhdpi/ic_launcher.png
  app/src/camp2015/res/mipmap-xxhdpi/ic_launcher.png
  app/src/camp2015/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/camp2015/res/values-de/strings.xml
  app/src/camp2015/res/values/colors.xml
  app/src/camp2015/res/values/colors_congress.xml
  app/src/camp2015/res/values/strings.xml
  app/src/camp2015/res/xml/track_resource_names.xml
Labels: Housekeeping, Project setup

#168 Verbalize when HTTP is used instead of HTTPS.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/HttpStatusExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CustomHttpClient.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/HttpStatus.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/HttpStatus.java
Labels: Networking, UX

#171 Portuguese translation updated.
  app/src/ccc35c3/res/values-pt/strings.xml
  app/src/cccamp2019/res/values-pt/strings.xml
  app/src/main/res/values-pt/preferences.xml
  app/src/main/res/values-pt/strings.xml
Labels: Translation

#177 Indicate which sessions are not video recorded in favorites list.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/LecturesAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/LectureChangesArrayAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/LectureArrayAdapter.kt
  app/src/main/res/drawable/ic_without_video_recording.png
  app/src/main/res/drawable/ic_without_video_recording_took_place.png
  app/src/main/res/layout/lecture_list_item.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
Labels: Feature request, UX

#179 Let TalkBack read out language abbreviations as full words.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/LectureChangesArrayAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/LectureArrayAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: UX
