Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-05, with the labels that each got.

#263 Faster navigate back from event detail to schedule view
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/CustomScrollView.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewColumnAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LecturesByRoomIndex.kt
  app/src/main/res/layout-port/schedule.xml
  app/src/main/res/layout/schedule_land.xml
  app/src/main/res/layout/schedule_land_large.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LecturesByRoomIndexTest.kt
Labels: Bug fix, UX

#264 Observing data - part 03
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Meta.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/FetchScheduleResult.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/res/layout-port/schedule.xml
  app/src/main/res/layout/schedule_land.xml
  app/src/main/res/layout/schedule_land_large.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensionsTest.kt
Labels: Architecture

#268 Clean up FahrplanFragment.loadLectureList()
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/RoomData.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleData.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformerTest.kt
Labels: Housekeeping

#269 Read alarm data in AppRepository.loadLecturesForDayIndex()
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
Labels: Housekeeping

#272 Customize menues and colors (details and alarms screens)
  app/src/main/res/drawable-v21/popup_background.xml
  app/src/main/res/values-v21/styles_congress.xml
  app/src/main/res/values-v22/styles_congress.xml
  app/src/main/res/values/styles_congress.xml
Labels: Design, UX

#274 Fix schedule view not starting to render on tablets.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.java
Labels: Bug fix, Tablets

#270 Remove MyApp static fields used to display the lecture list
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmList.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleData.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/OnLecturesChangeListener.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositoryLegacyTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformerTest.kt
Labels: Architecture

#280 Restore the "roomIndex fix"
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformer.kt
Labels: Bug fix, Layout arithmetic

#277 Remove view width magic
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.java
Labels: Housekeeping, Layout arithmetic
