Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-04, with the labels that each got.

#252 Encapsulate change calculations in new ChangeStatistic class.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeStatistic.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeStatisticTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMiscTest.kt
Labels: Housekeeping

#253 Unit test AlarmServices.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmList.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
Labels: Testing

#255 Random housekeeping
  .gitignore
  app/src/main/java/android/support/v4/app/SafeJobIntentService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmCursorAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/LecturesAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetail.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CertificateDialogFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/DomainNameChecker.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/TrustManagerFactory.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/OnShiftsLoadingDoneCallback.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/CustomScrollView.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TrackBackgrounds.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConferenceTimeFrame.java
  app/src/main/res/drawable/list_checked_background.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.java
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatter.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/temporal/DateParser.kt
Labels: Housekeeping

#257 Customizing menues and colors
  app/src/main/res/drawable/border.xml
  app/src/main/res/layout-port/schedule.xml
  app/src/main/res/layout-port/time_layout.xml
  app/src/main/res/layout-port/time_layout_now.xml
  app/src/main/res/layout/schedule_land.xml
  app/src/main/res/layout/schedule_land_large.xml
  app/src/main/res/layout/time_layout_land.xml
  app/src/main/res/layout/time_layout_land_large.xml
  app/src/main/res/layout/time_layout_now_land.xml
  app/src/main/res/layout/time_layout_now_land_large.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles_congress.xml
Labels: Design, UX

#241 JSON export of events and starred events for import into Chaosflix
  README.md
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/JsonLectureFormat.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/LectureSharer.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/FavoritesExport.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/LectureExport.kt
  app/src/main/res/menu/detailmenu.xml
  app/src/main/res/menu/starred_list_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/JsonLectureFormatTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Feature request

#258 Let getStartTimeMilliseconds() be a method of the Lecture class.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleLectureFormat.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/LectureTest.kt
Labels: Housekeeping

#256 Unit Test Lecture View Margin Calculation
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawerTest.kt
  build.gradle
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Housekeeping, Testing

#259 Observing data - part 02
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/MetaExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfo.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Meta.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/FetchScheduleResult.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/SharedPreferencesRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/MetaExtensionsTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensionsTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/contract/FahrplanContract.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Meta.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/MetaDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/MetaDBOpenHelper.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/Meta.kt
Labels: Architecture, Housekeeping

#262 Random housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/FetchScheduleResult.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChanges.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/LectureUtils.java
  app/src/main/res/layout-port/schedule.xml
  app/src/main/res/layout/schedule_land.xml
  app/src/main/res/layout/schedule_land_large.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/TestLogging.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeStatisticTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/NetworkScopeTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/TestExecutionContext.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawerTest.kt
Labels: Housekeeping
