Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-09, with the labels that each got.

#308 Restructure SharedPreferences usage
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/SharedPreferencesRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/preferences.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/preferences.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/preferences.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/preferences.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt/preferences.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/preferences.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/booleans.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/preferences.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/prefs.xml
Labels: Housekeeping, Persistence

#309 Use system's share UI when sharing a session as text
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SessionSharer.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SessionSharer.kt
Labels: Chaosflix, Sharing

#311 Retrieve non-null views where possible
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmCursorAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/ViewExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/C3navSnack.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.kt
Labels: Housekeeping

#310 Avoid using Intent.resolveActivity()
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/Contexts.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: Housekeeping

#313 Simplify code using Kotlin extensions
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/FragmentExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/IntentExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CertificateErrorFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
Labels: Housekeeping

#312 Modernize preferences implementation.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/notifications/NotificationHelper.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/AlarmTonePreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/SharedPreferencesRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/StyleableEditTextPreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/ValidateableEditTextPreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/AlarmToneConversion.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preferences.xml
  app/src/main/res/values/styles_congress.xml
  app/src/main/res/xml/prefs.xml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Housekeeping

#314 Random housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmList.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/AbstractListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CertificateErrorFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChanges.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConfirmationDialog.java
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: Housekeeping

#315 Use compileSdkVersion & targetSdkVersion 29 (Android 10).
  .travis.yml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#322 Log unit test execution events into console for all modules.
  app/build.gradle
  build.gradle
Labels: Testing
