Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-01, with the labels that each got.

#233 Preferences alternative schedule url
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/SharedPreferencesRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/preferences.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/preferences.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/preferences.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/preferences.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt/preferences.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/preferences.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/booleans.xml
  app/src/main/res/values/preferences.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/prefs.xml
Labels: Feature request

#234 Hide feedback button for wiki events because there is no feedback system.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/EventExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposerTest.kt
Labels: Bug fix

#235 Stop displaying alien URLs in Engelsystem shifts
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/EventUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/EventUrlComposerTest.kt
Labels: Bug fix

#236 Clear "subtitle" if it matches the "title" of a session.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensions.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensionsTest.kt
Labels: Housekeeping

#237 Allow to use logging in all modules.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/exceptions/AppExceptionHandler.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  commons/build.gradle
  commons/src/main/AndroidManifest.xml
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/ConsoleLogger.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/Logging.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/NoLogging.kt
  settings.gradle
Labels: Project setup

#239 Record debug information about zombie lecture which sometimes crashes the app.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  commons/build.gradle
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/AlmostNoLogging.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/ConsoleLogger.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/logging/Logging.kt
  database/build.gradle
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/LecturesDatabaseRepository.kt
Labels: Crash reporting

#240 RIP 35C3.
  README.md
  app/build.gradle
  app/gradle.properties.example
  app/src/ccc35c3/ic_launcher-web.png
  app/src/ccc35c3/res/drawable-anydpi-v24/ic_notification.xml
  app/src/ccc35c3/res/drawable-hdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-hdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-mdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-mdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-v24/ic_launcher_foreground.xml
  app/src/ccc35c3/res/drawable-xhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-xxhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xxhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable-xxxhdpi/dialog_logo.png
  app/src/ccc35c3/res/drawable-xxxhdpi/ic_notification.png
  app/src/ccc35c3/res/drawable/bell.png
  app/src/ccc35c3/res/drawable/ic_change_novideo.png
  app/src/ccc35c3/res/drawable/ic_change_video.png
  app/src/ccc35c3/res/drawable/ic_novideo.png
  app/src/ccc35c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc35c3/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/ccc35c3/res/mipmap-hdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-mdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xhdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xxhdpi/ic_launcher.png
  app/src/ccc35c3/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/ccc35c3/res/values-de/strings.xml
  app/src/ccc35c3/res/values-es/strings.xml
  app/src/ccc35c3/res/values-nl/strings.xml
  app/src/ccc35c3/res/values-pt/strings.xml
  app/src/ccc35c3/res/values-ru/strings.xml
  app/src/ccc35c3/res/values/colors.xml
  app/src/ccc35c3/res/values/colors_congress.xml
  app/src/ccc35c3/res/values/ic_launcher_background.xml
  app/src/ccc35c3/res/values/strings.xml
  app/src/ccc35c3/res/xml/track_resource_names.xml
  gfx/EventFahrplan-35c3-Events-Tablet-Phone.png
  gfx/EventFahrplan-36c3-Events-Tablet-Phone.png
Labels: Housekeeping, Project setup

#215 Clean up LecturesDatabaseRepository
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/AlarmsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/LecturesDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/MetaDatabaseRepository.kt
Labels: Housekeeping, Persistence

#210 Only use signingConfig when relevant properties are set
  README.md
  app/build.gradle
Labels: Project setup

#242 Prevent crashes caused by closed database connections.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmList.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SQLiteDatabaseExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/AlarmsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/LecturesDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/MetaDatabaseRepository.kt
Labels: Bug fix, Persistence

#225 #195 update notification channels on locale changed event
  app/src/main/AndroidManifest.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/notifications/NotificationHelper.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnLocaleChangedReceiver.kt
Labels: Bug fix, Translation
