Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-10, with the labels that each got.

#332 Added Swedish translations.
  app/src/ccc36c3/res/values-sv/strings.xml
  app/src/main/res/values-sv/preferences.xml
  app/src/main/res/values-sv/strings.xml
Labels: Hacktoberfest, Translation

#331 Portuguese translations
  app/src/main/res/values-pt/preferences.xml
  app/src/main/res/values-pt/strings.xml
Labels: Hacktoberfest, Translation

#334 japanese translation for strings.xml and preferences.xml
  app/src/ccc36c3/res/values-ja/strings.xml
  app/src/cccamp2019/res/values-ja/strings.xml
  app/src/main/res/values-ja/preferences.xml
  app/src/main/res/values-ja/strings.xml
Labels: Hacktoberfest, Translation

#335 Update German translation and English strings
  app/src/main/res/values-de/placeholder.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Housekeeping, Translation

#330 Spanish by subtle
  app/src/main/res/values-es/preferences.xml
  app/src/main/res/values-es/strings.xml
Labels: Hacktoberfest, Translation

#336 Random housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ConnectivityObserver.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/StyleableEditTextPreference.kt
  app/src/main/res/values/styles_congress.xml
Labels: Housekeeping

#284 Decrease build time.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
Labels: Project setup
