Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-03, with the labels that each got.

#247 Do not render "Schedule " prefix when schedule version is not provided.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
Labels: UX

#245 Centralize date handling
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/LecturesAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/LectureChangesArrayAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LecturesExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/LectureArrayAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfo.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfo.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DayRange.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/Conference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGenerator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TimeSegment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleLectureFormat.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/DateHelper.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/LectureExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DateInfoTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DayRangeTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/LectureTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ConferenceTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGeneratorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/TimeSegmentTest.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChangesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/DateHelperTest.kt
  commons/build.gradle
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatter.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DayRange.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatterTest.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Lecture.kt
  network/build.gradle
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/temporal/DateParser.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/utils/DateHelper.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidation.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidation.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DateParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/utils/DateHelperTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidationTest.kt
Labels: Date & time, Housekeeping

#249 Observing data - part 01
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositoryLecturesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositoryLegacyTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMiscTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SQLiteDatabaseExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/AlarmsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt
Labels: Architecture
