Repository EventFahrplan/EventFahrplan, pull requests merged in 2020-07, with the labels that each got.

#282 Don't use Lecture.roomIndex in the UI layer
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleData.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/LectureListTransformer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LecturesByRoomIndex.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleDataTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculatorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LecturesByRoomIndexTest.kt
Labels: Housekeeping, Layout arithmetic

#288 Lecture alarms housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
Labels: Housekeeping

#287 Random housekeeping
  app/src/ccc36c3/res/values/colors_congress.xml
  app/src/cccamp2019/res/values/colors_congress.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/HttpStatusExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LectureViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TrackBackgrounds.java
  app/src/main/res/drawable-hdpi/ic_calendar_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_calendar_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_calendar_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_calendar_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_calendar_white_24dp.png
  app/src/main/res/layout-port/event_layout.xml
  app/src/main/res/menu/detailmenu.xml
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/LectureTest.kt
Labels: Housekeeping

#286 Remove discontinued kotlin-coroutines-retrofit dependency.
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  engelsystem/build.gradle
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/EngelsystemNetworkRepository.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoading.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/models/ShiftsResult.kt
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoadingTest.kt
Labels: Engelsystem, Project setup

#281 DateParser: implement parsing of local datetimes, add test cases
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DateParserTest.kt
Labels: Date & time

#291 Add "commons-testing" module to DRY tests.
  app/build.gradle
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositorySessionsTest.kt
  commons-testing/build.gradle
  commons-testing/src/main/AndroidManifest.xml
  commons-testing/src/main/java/info/metadude/android/eventfahrplan/commons/testing/Verification.kt
  settings.gradle
Labels: Housekeeping, Testing

#292 Use convenience functions provided by "core-ktx" artifact.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/commons/TextViewCompat.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/Contexts.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/TextViewExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ConnectivityObserver.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/SharedPreferencesRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/ValidateableEditTextPreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/EngelsystemUrlValidator.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  database/build.gradle
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/AlarmExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/HighlightExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SQLiteDatabaseExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/SessionsDatabaseRepository.kt
Labels: Housekeeping

#294 Replace deprecated "Html#fromHtml" with "HtmlCompat#fromHtml".
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/extensions/StringExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.java
Labels: Housekeeping

#295 Revise Session equals & hashCode methods
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
Labels: Housekeeping
