Repository EventFahrplan/EventFahrplan, pull requests merged in 2021-12, with the labels that each got.

#408 Improve TalkBack accessibility of session texts
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmCursorAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SelectedSessionParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarDescriptionComposerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharingTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChangesTest.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatter.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatterTest.kt
Labels: UX, Favorites, Schedule changes, Session details

#422 Prepare schedule screen rewrite (unidirectional data flow)
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfo.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CertificateErrorFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/Conference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGenerator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TimeTextViewParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/TypefaceFactory.kt
  app/src/main/res/menu/fahrplan_menu.xml
  app/src/main/res/menu/mainmenu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositorySessionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGeneratorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculatorTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Session.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/Session.kt
Labels: Architecture, Housekeeping

#425 Use engelsystem v.6.0.0.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensions.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensionsTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoadingTest.kt
Labels: Engelsystem

#426 Introduce a Polish translation of EventFahrplan
  README.md
  app/src/ccc36c3/res/values-pl/strings.xml
  app/src/cccamp2019/res/values-pl/strings.xml
  app/src/main/res/values-pl/preferences.xml
  app/src/main/res/values-pl/strings.xml
  app/src/rc3/res/values-pl/strings.xml
Labels: Translation

#424 Let AppRepository be the single source of truth for schedule screen.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeStatistic.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ErrorMessage.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/LoadScheduleState.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/OnSessionsChangeListener.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGenerator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/FahrplanEmptyParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/FahrplanParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/LoadScheduleUiState.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/ScheduleChangesParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/ScrollToCurrentSessionParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/ScrollToSessionParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/TimeTextViewParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/TypefaceFactory.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositorySessionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/MainViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/TimeTextViewParameterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMiscTest.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: UX, Architecture, Scrolling, Schedule grid

#428 Protect UpdateService work from being interrupted before loading is done.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
Labels: Architecture

#429 Ease translation process by excluding library names.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/res/layout/about_dialog.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
Labels: Translation, Housekeeping
