Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-07, with the labels that each got.

#487 Update project setup (Kotlin 1.7.10, AppCompat 1.4.2, core-ktx 1.8.0)
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#486 Add loading spinner while starred lectures are loading
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt
  app/src/main/res/layout/fragment_favorites_list.xml
  app/src/main/res/layout/fragment_favorites_list_narrow.xml
  app/src/main/res/values/dimens.xml
Labels: UX, Favorites

#489 Clarify behavior of navigation menu entries generator
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGenerator.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGeneratorTest.kt
Labels: Housekeeping

#490 Fix broken automatic redraw when settings are changed.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.kt
Labels: Bug fix, App settings

#492 Update project setup (AGP 7.1.2, Coroutines 1.6.4)
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Project setup
