Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-02, with the labels that each got.

#456 Fix crash when attempting to send stacktrace.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.java
Labels: Bug fix, Crash reporting

#457 Only show horizontal progress bar when schedule loading takes longer.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.kt
  app/src/main/res/layout-port/main_layout.xml
  app/src/main/res/layout/main_layout_land.xml
  app/src/main/res/layout/main_layout_land_large.xml
  app/src/main/res/layout/main_layout_land_large_split.xml
Labels: UX

#460 Add initial GitHub workflow
  .github/workflows/build.yaml
  app/build.gradle
  commons-testing/build.gradle
Labels: Project setup
