Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-08, with the labels that each got.

#497 Engage users to learn about using the app in landscape mode.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/Engagements.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/LandscapeOrientationSnack.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  docs/CUSTOMIZING.md
Labels: Feature request, UX

#494 Fix Overscroll Behavior in Android 12+
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollState.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollStateTest.kt
Labels: UX, Bug fix, Scrolling, Schedule grid

#498 Let Crowdin only list files which contain translatable strings.
  crowdin.yml
Labels: Project setup, Translation
