Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-01, with the labels that each got.

#434 Fix display errors in the favorites scroll bar and the change screen
  app/src/main/res/layout/fragment_favorites_list.xml
  app/src/main/res/layout/fragment_favorites_list_narrow.xml
  app/src/main/res/layout/fragment_session_list.xml
  app/src/main/res/layout/fragment_session_list_narrow.xml
Labels: Bug fix, Favorites, Scrolling, Schedule changes

#433 Fix crash when tapping feedback icon in details screen.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
Labels: Bug fix, Feedback

#436 Append social media hashtags/handles if present when sharing a session
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormat.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormatTest.kt
  docs/CUSTOMIZING.md
Labels: Feature request, Sharing

#438 Reduce duration of Travis CI builds
  .travis.yml
Labels: Project setup

#437 Random housekeeping + changes dialog translations
  README.md
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/res/layout/fragment_favorites_list.xml
  app/src/main/res/layout/fragment_session_list.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  docs/CUSTOMIZING.md
Labels: Project setup, Translation, Housekeeping, Favorites, Schedule changes

#442 Housekeeping for session item text colors
  app/src/ccc36c3/res/values/colors_congress.xml
  app/src/cccamp2019/res/values/colors_congress.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/res/layout-port/session_layout.xml
  app/src/main/res/layout/session_layout_land.xml
  app/src/main/res/layout/session_layout_land_large.xml
  app/src/main/res/values/colors.xml
  app/src/rc3/res/values/colors_congress.xml
Labels: Schedule grid

#443 Update project setup (Gradle 7.3.3, ConstraintLayout 2.1.3, Kotlin 1.6.10 + Moshi 1.13.0 + KSP)
  .travis.yml
  app/build.gradle
  build.gradle
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  engelsystem/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Project setup

#444 Changed "Thomaeum Kempen" to "isi_ko404"
  README.md
  app/src/main/res/values/strings.xml
Labels: Documentation

#445 removed "large" version of Detailbar
  app/src/main/res/layout/detail_land_large.xml
  app/src/main/res/layout/detail_large.xml
  app/src/main/res/layout/detail_narrow_large.xml
  app/src/main/res/layout/session_detailbar.xml
  app/src/main/res/layout/session_detailbar_large.xml
Labels: Housekeeping, Session details

#447 Adding custom scrollbar
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt
  app/src/main/res/drawable/scrollbar_thumb.xml
  app/src/main/res/layout/alarms.xml
  app/src/main/res/layout/fragment_favorites_list.xml
  app/src/main/res/layout/fragment_favorites_list_narrow.xml
  app/src/main/res/layout/fragment_session_list.xml
  app/src/main/res/layout/fragment_session_list_narrow.xml
  app/src/main/res/layout/session_detailbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles_congress.xml
  app/src/rc3/res/values/colors.xml
Labels: App settings, Favorites, Scrolling, Schedule changes, Session details

#450 Used 'Horizontal' and 'Vertical' Margin and Paddings
  app/src/main/res/layout/about_dialog.xml
  app/src/main/res/layout/alarm_list_item.xml
  app/src/main/res/layout/detail_land_large.xml
  app/src/main/res/layout/detail_large.xml
  app/src/main/res/layout/detail_narrow.xml
  app/src/main/res/layout/detail_narrow_large.xml
  app/src/main/res/layout/fragment_favorites_list_narrow.xml
  app/src/main/res/layout/fragment_session_list_narrow.xml
  app/src/main/res/layout/session_detailbar.xml
  app/src/main/res/layout/session_list_item.xml
  app/src/main/res/layout/session_list_separator.xml
  app/src/main/res/layout/session_list_separator_land_large.xml
  app/src/main/res/layout/settings_widget_open_external.xml
Labels: Housekeeping

#449 Transpile to Kotlin: BundleKeys
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/contract/BundleKeys.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
Labels: Housekeeping

#453 Transpile to Kotlin: utils package
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ActivityHelper.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ActivityHelper.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConfirmationDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConfirmationDialog.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.kt
Labels: Housekeeping

#454 Transpile to Kotlin: base package
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/AbstractListFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/AbstractListFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/BaseActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.kt
Labels: Housekeeping, Favorites, Schedule changes

#455 Transpile MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
Labels: Housekeeping
