Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-09, with the labels that each got.

#495 Transpile minor classes
  app/src/main/java/androidx/core/app/SafeJobIntentService.java
  app/src/main/java/androidx/core/app/SafeJobIntentService.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangesDialog.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/exceptions/BuilderException.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/exceptions/BuilderException.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/reporting/TraceDroidEmailSender.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sidepane/OnSidePaneCloseListener.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sidepane/OnSidePaneCloseListener.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.kt
Labels: Housekeeping

#499 Support configuring custom names for "Engelsystem" and "Engelshifts".
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ErrorMessage.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/res/values-de/preferences.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/preferences.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/preferences.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/preferences.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/preferences.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/preferences.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/preferences.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-sv/preferences.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/preferences.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
  docs/CUSTOMIZING.md
Labels: Feature request, Engelsystem

#500 Update project setup (AGP 7.2.2, ThreeTenBp 1.6.1)
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: Project setup

#501 Show "track" in session details screen.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SelectedSessionParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/res/layout/session_details_content.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
Labels: Feature request, Session details

#502 Update GitHub templates
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Project setup

#503 Transpile net Package
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CustomHttpClient.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/CustomHttpClient.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/HttpStatus.kt
Labels: Housekeeping

#505 Transpile Network Code
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/HttpStatus.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/exceptions/MissingXmlAttributeException.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/exceptions/MissingXmlAttributeException.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/validation/ValidationError.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/validation/ValidationError.kt
Labels: Housekeeping

#511 Support configuring the postal address of the event
  app/build.gradle
  app/src/ccc36c3/res/values-de/strings.xml
  app/src/ccc36c3/res/values-es/strings.xml
  app/src/ccc36c3/res/values-fr/strings.xml
  app/src/ccc36c3/res/values-ja/strings.xml
  app/src/ccc36c3/res/values-nl/strings.xml
  app/src/ccc36c3/res/values-pl/strings.xml
  app/src/ccc36c3/res/values-pt/strings.xml
  app/src/ccc36c3/res/values-ru/strings.xml
  app/src/ccc36c3/res/values-sv/strings.xml
  app/src/ccc36c3/res/values/strings.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.kt
  app/src/main/res/layout/about_dialog.xml
  docs/CUSTOMIZING.md
Labels: Feature request

#509 Transpile 'DateInfos.java' Class
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
Labels: Housekeeping, Date & time

#508 Transpile Alarms Package
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
Labels: Housekeeping
