Repository EventFahrplan/EventFahrplan, pull requests merged in 2022-03, with the labels that each got.

#468 Transpile SessionDrawable and TrackBackgrounds to Kotlin.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionDrawable.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionDrawable.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TrackBackgrounds.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/TrackBackgrounds.kt
Labels: Housekeeping, Schedule grid

#469 Simplify build flavor configuration for new events.
  app/build.gradle
Labels: Project setup

#471 Use Coroutines v.1.6.0.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainViewModel.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositorySessionsTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  commons-testing/src/main/java/info/metadude/android/eventfahrplan/commons/testing/MainDispatcherTestRule.kt
  engelsystem/build.gradle
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoadingTest.kt
Labels: Project setup

#472 Update project setup (Gradle wrapper 7.4.1, ThreeTenBp 1.6.0, AGP 7.1.2)
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Project setup

#473 Replace deprecated target fragment API with FragmentResultListener API.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConfirmationDialog.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/TimeTextViewParameterTest.kt
Labels: Housekeeping, Alarms

#474 Use compileSdk & targetSdk 31 (Android 12).
  app/src/main/AndroidManifest.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/PendingIntentCompat.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#475 Update project setup (Multidex, Preference 1.2.0, core-ktx 1.7.0, AppCompat 1.4.1, lifecycle-livedata-ktx 2.4.1, Material 1.5.0)
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/AlarmTonePreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  build.gradle
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  commons-testing/build.gradle
  commons/build.gradle
Labels: Project setup

#476 Use engelsystem v.7.0.0.
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  engelsystem/build.gradle
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/EngelsystemNetworkRepository.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/EngelsystemServiceProvider.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoading.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/models/ShiftsResult.kt
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/EngelsystemNetworkRepositoryTest.kt
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/loading/ShiftsLoadingTest.kt
Labels: Project setup, Engelsystem

#477 Clean up logging.
  app/src/main/java/androidx/core/app/SafeJobIntentService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmList.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/autoupdate/UpdateService.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeStatistic.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/HorizontalSnapScrollView.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsActivity.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnLocaleChangedReceiver.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/AlarmsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/MetaDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/SessionsDatabaseRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/repositories/ScheduleNetworkRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidation.kt
Labels: Architecture, Housekeeping

#478 Ease sharing text from error message alert dialog.
  app/src/main/res/values/styles_congress.xml
Labels: Feature request, UX
