Repository EventFahrplan/EventFahrplan, pull requests merged in 2023-12, with the labels that each got.

#576 Restrict landscape mode engagement to be shown only in portrait mode.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/IsInPortraitOrientation.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/LandscapeOrientationSnack.kt
Labels: UX, Bug fix

#577 Restrict Google Play engagements to be shown only when installed via this store.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/GooglePlayBetaTestingSnack.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/IsInstalledViaGooglePlay.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/engagements/RateSnack.kt
Labels: UX, Bug fix, Engagements

#578 Allow customizing the text color for room name headers.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
Labels: Design, Bug fix

#579 Use device time zone by default to display sessions with local times.
  app/src/main/res/values/preferences.xml
Labels: Date & time

#580 Update project setup (Compose compiler 1.5.6, kotlin 1.9.21, mockito 5.8.0, mockito-kotlin 5.2.1, command line tools 9862592)
  .travis.yml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#582 Fix article not matching the grammatical gender of the conference name.
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug fix, Indoor navigation, Engagements

#583 Add support for indoor navigation (c3nav) based on room guid.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SelectedSessionParameter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Room.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleData.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/C3nav.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/IndoorNavigation.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChanges.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormat.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/SessionUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharingTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleDataTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/navigation/C3navGetUriTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/navigation/C3navIsSupportedTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculatorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculatorTimeZoneOffsetTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/TimeTextViewParameterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChangesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormatTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/SessionUrlComposerTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensionsTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/contract/FahrplanContract.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Session.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/RealSessionsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/SessionsDBOpenHelper.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/Session.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: Feature request, Housekeeping, Indoor navigation, Persistence

#584 Random housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/JsonSessionFormatTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/SessionsDBOpenHelper.java
Labels: Housekeeping, Indoor navigation, Sharing

#585 Add support for the dedicated feedback URL field.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposer.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposerTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensionsTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/contract/FahrplanContract.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Session.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/RealSessionsDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/SessionsDBOpenHelper.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/Session.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: Feature request, Persistence, Feedback

#586 Cleanup Session class to its prepare migration to Kotlin data class
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/calendar/CalendarSharing.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Session.java
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/Conference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormat.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/LayoutCalculatorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculatorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/TimeTextViewParameterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleSessionFormatTest.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
Labels: Housekeeping

#587 Add ccc37c3 product flavor
  .github/workflows/build.yaml
  .travis.yml
  app/build.gradle
  app/gradle.properties.example
  app/src/ccc37c3/ic_launcher-playstore.png
  app/src/ccc37c3/res/drawable-anydpi-v24/ic_notification.xml
  app/src/ccc37c3/res/drawable-hdpi/ic_notification.png
  app/src/ccc37c3/res/drawable-mdpi/ic_notification.png
  app/src/ccc37c3/res/drawable-xhdpi/ic_notification.png
  app/src/ccc37c3/res/drawable-xxhdpi/ic_notification.png
  app/src/ccc37c3/res/drawable-xxxhdpi/ic_notification.png
  app/src/ccc37c3/res/drawable/dialog_logo.xml
  app/src/ccc37c3/res/drawable/ic_launcher_foreground.xml
  app/src/ccc37c3/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/ccc37c3/res/mipmap-hdpi/ic_launcher.webp
  app/src/ccc37c3/res/mipmap-mdpi/ic_launcher.webp
  app/src/ccc37c3/res/mipmap-xhdpi/ic_launcher.webp
  app/src/ccc37c3/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/ccc37c3/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/ccc37c3/res/values-de/strings.xml
  app/src/ccc37c3/res/values-es/strings.xml
  app/src/ccc37c3/res/values-fr/strings.xml
  app/src/ccc37c3/res/values-ja/strings.xml
  app/src/ccc37c3/res/values-nl/strings.xml
  app/src/ccc37c3/res/values-pl/strings.xml
  app/src/ccc37c3/res/values-pt/strings.xml
  app/src/ccc37c3/res/values-ru/strings.xml
  app/src/ccc37c3/res/values-sv/strings.xml
  app/src/ccc37c3/res/values/colors.xml
  app/src/ccc37c3/res/values/colors_congress.xml
  app/src/ccc37c3/res/values/ic_launcher_background.xml
  app/src/ccc37c3/res/values/strings.xml
  app/src/ccc37c3/res/xml/track_resource_names.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/AlarmsDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/HighlightDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/MetaDBOpenHelper.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/SessionsDBOpenHelper.java
Labels: Project setup, Engelsystem

#561 Add parser for the duration value in the Fahrplan XML
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/temporal/DurationParser.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DurationParserTest.kt
Labels: Bug fix, Date & time
