Repository EventFahrplan/EventFahrplan, pull requests merged in 2024-01, with the labels that each got.

#602 Consistently use Moment class to process date & time values
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/MyApp.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdater.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConferenceTimeFrame.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/FahrplanMisc.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/MyAppTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/ConferenceTimeFrameTest.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
Labels: Housekeeping, Date & time, Schedule updates

#603 Display session subtitle as title if the latter is empty.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
Labels: Housekeeping, Engelsystem

#605 Refactor ConferenceTimeFrame to use closed range internally.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/ConferenceTimeFrame.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
Labels: Housekeeping, Date & time, Schedule updates

#597 Correct the JSON output for the share action
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/JsonSessionFormatTest.kt
Labels: Bug fix, Chaosflix, Sharing

#604 Support caching via "Last-Modified" & "If-Modified-Since" HTTP headers.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/HttpHeaderExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/MetaExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/HttpHeader.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Meta.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/MetaExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositoryLoadAndParseScheduleTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensionsTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/contract/FahrplanContract.java
  database/src/main/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensions.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/HttpHeader.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/models/Meta.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/RealMetaDatabaseRepository.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/sqliteopenhelper/MetaDBOpenHelper.java
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchScheduleResult.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/HttpHeader.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/models/Meta.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/repositories/RealScheduleNetworkRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/repositories/ScheduleNetworkRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: Persistence, Networking

#606 Fix NavigationMenuEntriesGenerator creating wrong number of menu entries.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionsExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/VirtualDay.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGenerator.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/observables/FahrplanParameter.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionsExtensionsToVirtualDaysTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/VirtualDayTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGeneratorTest.kt
Labels: Bug fix, Engelsystem, Date & time

#607 Random housekeeping
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/ScrollAmountCalculator.kt
  app/src/main/res/layout/about_dialog.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/serialization/ScheduleChangesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/sharing/JsonSessionFormatTest.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt
Labels: Housekeeping

#608 Add link to translation platform to "info" screen.
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/about/AboutDialog.kt
  app/src/main/res/layout/about_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Feature request

#609 Update translations (Swedish, Lithuanian, Turkish).
  README.md
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/preferences.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/xml/locales_config.xml
  crowdin.yml
Labels: Translation

#610 Update project setup (mockito 5.9.0, truth 1.2.0).
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
Labels: Project setup

#611 Protect BroadcastReceiver in ConnectivityObserver from access by external apps.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/net/ConnectivityObserver.kt
Labels: Housekeeping, Networking

#615 Improve error message with disabled notifications on devices running older than Android 13 (Tiramisu).
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/notifications/NotificationHelper.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
Labels: Housekeeping, Notifications, Alarms, Android permissions

#614 Support scheduling exact alarms for sessions.
  app/src/main/AndroidManifest.xml
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServices.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/SessionAlarmViewModelDelegate.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmServicesTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/SessionAlarmViewModelDelegateTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanViewModelTest.kt
Labels: Bug fix, Notifications, Alarms, Android permissions
