Repository EventFahrplan/EventFahrplan, pull requests merged in 2024-02, with the labels that each got.

#616 Update GitHub actions setup
  .github/workflows/build.yaml
Labels: Project setup, Testing

#618 Update project setup (Compose compiler 1.5.9, kotlin 1.9.22, moshi 1.15.1, engelsystem 8.1.0, Gradle 7.6.4)
  .github/workflows/build.yaml
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: Project setup

#620 Run builds on Ubuntu 22.04 (Jammy) on Travis CI.
  .travis.yml
Labels: Project setup

#621 Continue to display parsing error when schedule data cannot be parsed.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositoryLoadAndParseScheduleTest.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/repositories/RealScheduleNetworkRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/repositories/ScheduleNetworkRepository.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java
Labels: Bug fix, Housekeeping, Persistence, Networking, Schedule updates

#622 Random housekeeping (KDoc, test names, duplication, verbosity).
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/VirtualDay.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DateInfoTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DayRangeTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/SessionUrlComposerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/wiki/WikiSessionUtilsTest.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
  engelsystem/src/test/kotlin/info/metadude/android/eventfahrplan/engelsystem/utils/UriParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DateParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DurationParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidationTest.kt
Labels: Housekeeping, Testing, Documentation

#624 Fix flaky Moment tests.
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
Labels: Bug fix, Testing, Date & time

#623 Migrate remaining tests from AssertJ to Truth.
  app/build.gradle
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmUpdaterTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/AlarmExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/FetchScheduleResultExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/HighlightExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/MetaExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/ShiftsExtensionsTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DateInfoTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/DayRangeTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/ScheduleDataTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/models/SessionTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/NetworkScopeTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/NavigationMenuEntriesGeneratorTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/schedule/TimeSegmentTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/FeedbackUrlComposerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/utils/SessionUrlComposerTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/wiki/WikiSessionUtilsTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  commons/build.gradle
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatterTest.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/MomentTest.kt
  database/build.gradle
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/AlarmExtensionsTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/HighlightExtensionsTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/MetaExtensionsTest.kt
  database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions/SessionExtensionsTest.kt
  network/build.gradle
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DateParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/temporal/DurationParserTest.kt
  network/src/test/java/info/metadude/android/eventfahrplan/network/validation/DateFieldValidationTest.kt
Labels: Project setup, Testing

#627 Speed up CI by not starting an emulator for unit tests
  .github/workflows/build.yaml
Labels: Project setup

#628 Allow to customize the color of list items.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/res/values/colors.xml
Labels: Design
