Repository EventFahrplan/EventFahrplan, pull requests merged in 2025-01, with the labels that each got.

#704 Create new activity task when launching navigation
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
Labels: UX, Indoor navigation

#710 Fix crash at reboot (OnBootReceiver).
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/system/OnBootReceiver.kt
Labels: Bug fix, Alarms, Schedule updates

#712 Update project setup (AGP 8.8.0, Jetpack Compose UI 2024.12.01, kotlin 2.1.0, coroutines 1.10.1, Gradle 8.12).
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Project setup

#713 Update Polish and Lithuanian translations.
  README.md
  app/src/main/res/values-lt/preferences.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: Translation

#715 Random housekeeping (crash report, headline flickering, identical texts, schedule changes color contrast).
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmTimePickerFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensions.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/preferences/ValidateableEditTextPreference.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/SessionViewDrawer.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/settings/SettingsFragment.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles_congress.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/dataconverters/SessionExtensionsTest.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateParser.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/DateParserTest.kt
  database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/RealSessionsDatabaseRepository.kt
  engelsystem/src/main/java/info/metadude/android/eventfahrplan/engelsystem/utils/UriParser.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/fetching/FetchFahrplan.kt
  network/src/main/java/info/metadude/android/eventfahrplan/network/temporal/DurationParser.kt
Labels: UX, Housekeeping, Schedule changes, Session details

#716 Show room state in details screen (FOSDEM only).
  README.md
  app/build.gradle
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/commons/BuildConfigProvider.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/commons/BuildConfigProvision.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModel.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelFactory.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/roomstates/RoomStateFormatter.kt
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/roomstates/RoomStateFormatting.kt
  app/src/main/res/layout/session_details_content.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/about/AboutParameterFactoryTest.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsViewModelTest.kt
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  docs/CUSTOMIZING.md
Labels: Feature request, Room states
