Repository EventFahrplan/EventFahrplan, pull requests merged in 2025-06, with the labels that each got.

#754 Update project setup (fragment-compose 1.8.8, appcompat 1.7.1, htmlconverter 1.0.4, kotlin 2.1.21, ksp 2.1.21-2.0.1, AGP 8.10.1).
  buildSrc/src/main/kotlin/nerd/tuxmobil/fahrplan/congress/Dependencies.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Project setup

#759 Unit test ZoneOffsetProvider#getAvailableZoneOffset.
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateFormatter.kt
  commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/ZoneOffsetProvider.kt
  commons/src/test/java/info/metadude/android/eventfahrplan/commons/temporal/ZoneOffsetProviderTest.kt
Labels: Testing, Date & time

#761 Fix that selecting a day menu item does not cause the UI to redraw.
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepositorySessionsWithoutShiftsTest.kt
Labels: Bug fix, Schedule grid

#758 Add FakeFormattingDelegate to remove dependence on device's locale
  app/src/test/java/nerd/tuxmobil/fahrplan/congress/alarms/AlarmsStateFactoryTest.kt
Labels: Bug fix, Testing

#482 Optimize Room View Update
  app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
Labels: UX, Bug fix, Schedule grid
